name: CorporateCraft
main: me.backspace119.CorporateCraft
version: 0.3
description: >
             Corporation plugin to implement companies into Bukkit
commands:
  cc:
    description: displays info on plugin
  cc h:
    description: heals a/the player
  cc heal:
    description: Heals a/the player.
  cc test-permission:
    description: tests a permission
  cc Start:
    description: starts a new company with <name> and starts and account for it charges price set by server
  cc Defaults:
    description: saves default config of plugin to disc overwriting current configuration
  cc Reload: 
    description: reloads configuration for plugin
  cc Access:
    description: access a company bank account
  cc SetHiring:
    description: set whether a company is hiring
  cc Hiring:
    description: see which companies are hiring
  cc Reset:
    description: resets companies.yml data HANDLE WITH CARE!
  cc Hire:
    description: hire an employee WARNING HIRING IS PER WORLD AND ONLY VALID IN THE WORLD THE PLAYER IS STANDING IN!
  cc setDescription:
    description: set a description for a company
  cc Info:
    description: see the description and other info of a company
  cc Apply:
    description: apply for a job at a hiring company
  cc addRegion:
    description: adds a region to a companies list and the server wide list WARNING ONLY VALID IN THE WORLD THE PLAYER IS STANDING IN AT CURRENT MOMENT!
  cc ChangeCompany:
    description: sets a players company assignment to a different one //cc ChangeCompany <player> <company>
  cc GetProduct:
    description: gets the product created by company employees
  cc addKeep:
    description: adds an item id to keep from employees leaving a company plot
  cc removeKeep:
    description: removes an item id to keep from employees leaving a company plot
permissions:
  corporatecraft.*:
    description: gives access to all corporatecraft commands
    children:
      corporatecraft.ccStart: true
      corporatecraft.ccReload: true
      corporatecraft.ccDefaults: true
      corporatecraft.test-permission: true
      corporatecraft.override.*: true
      corporatecraft.override.regions: true
  corporatecraft.test-permission:
    description: a test permission
    default: true
  corporatecraft.override.*:
    description: gives access to all overriding commands and events HANDLE WITH CARE!
    default: false
    children: 
      corporatecraft.override.regions: true
      corporatecraft.override.setCompany: true
  corporatecraft.admin.*:
    description: gives admin perms to the player--not quite as powerful as override
    default: false
    children:
      corporatecraft.admin.setCompany: true
depend: [Vault, WorldGuard, WGCustomFlags, WGRegionEvents]